### ISSUE TITLE
OpenAPI descriptions by eToro

### ISSUE THREAD

**Issue by redindian** [mkhaled87/etoro-api#1]
Hi, thanks for sharing this! I've been trying to find the OpenAPI descriptions on the eToro API website, but all I can find are GET endpoints. Where did you find these OpenAPI descriptions?

**Comment by mkhaled87** [comment]
I assume you refer to the eToro developer portal. There, you can only view GET endpoints as a non-user. Once you login, you can access the rest of  API.
