### ISSUE TITLE
Is this API still actibe?

### ISSUE THREAD

**Issue by jcabourne** [mkhaled87/etoro-api#3]
Hi is this API wrapper still working? When i click through to the Etoro trading API links to read the etoro docs the websites are no longer there and i cant find any information online for Etoro Trading API.

for example
https://api.etoro.com/API/Trading/V1

**Comment by mkhaled87** [comment]
Documentation is still available here:
[https://api-portal.etoro.com/docs/services/](https://api-portal.etoro.com/docs/services/)
However, usage/access requires a subscription (see your profile page).

**Comment by pascalranoroarijaona** [comment]
Hi @mkhaled87 how can I can a subscription enabled I don't know how to create an account on the website and my etoro credentials don't seem to work? I have been in touch with eToro Support and Account manager with no luck so far.
Thanks very much!

**Comment by mkhaled87** [comment]
@pascaloberle: It seems eToro is no longer giving new accounts/subscriptions.  I can't think of any other way but to try to contact them.
